__Python: NumPy__

In [27]:
import numpy as np
a = np.array([7,8,9,10,11])
print(f'{a}\n{"object type:":>12} {type(a)}\n{"data type:":>12} {a.dtype} \
\n{"shape:":>12} {a.shape}\n{"dimension:":>12} {a.ndim} \
\n{"array_size:":>12} {a.size} \
')

b = [7,8,9,10,11]
print(b)

a1 = np.array([a])
print(a1)
print(a1.shape)

[ 7  8  9 10 11]
object type: <class 'numpy.ndarray'>
  data type: int32 
      shape: (5,)
  dimension: 1 
 array_size: 5 
[7, 8, 9, 10, 11]
[[ 7  8  9 10 11]]
(1, 5)


In [32]:
b = np.array([[1.0, 2, 3, 4, 5], [8,9,10,11, 12.2]])
print(f'{b}\n{"object type:":>12} {type(b)} \
\n{"data type:":>12} {b.dtype} \
\n{"shape:":>12} {b.shape} \
\n{"dimension:":>12} {b.ndim} \
\n{"array_size:":>12} {b.size} \
')

[[ 1.   2.   3.   4.   5. ]
 [ 8.   9.  10.  11.  12.2]]
object type: <class 'numpy.ndarray'> 
  data type: float64 
      shape: (2, 5) 
  dimension: 2 
 array_size: 10 


In [34]:
c = np.array([[[1, 2, 3, 4, 5], [8,9,10,11,12]], [[4, 5,6,7,8], [10,11,12,13,14]]])
print(f'{c}\n{"object type:":>12} {type(c)} \
\n{"data type:":>12} {c.dtype} \
\n{"shape:":>12} {c.shape} \
\n{"dimension:":>12} {c.ndim} \
\n{"array_size:":>12} {c.size} \
')

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]

 [[ 4  5  6  7  8]
  [10 11 12 13 14]]]
object type: <class 'numpy.ndarray'> 
  data type: int32 
      shape: (2, 2, 5) 
  dimension: 3 
 array_size: 20 


In [35]:
ac1 = np.array([[[1, 2, 3, 4, 5], [8,9,10,11,12]]])
print(f'{ac1}\n{"object type:":>12} {type(ac1)} \
\n{"data type:":>12} {ac1.dtype} \
\n{"shape:":>12} {ac1.shape} \
\n{"dimension:":>12} {ac1.ndim} \
\n{"array_size:":>12} {ac1.size} \
')

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]]
object type: <class 'numpy.ndarray'> 
  data type: int32 
      shape: (1, 2, 5) 
  dimension: 3 
 array_size: 10 


In [39]:
ac2 = np.array([[[1, 2, 3, 4, 5]]])
print(f'{ac2}\n{"object type:":>12} {type(ac2)} \
\n{"data type:":>12} {ac2.dtype} \
\n{"shape:":>12} {ac2.shape} \
\n{"dimension:":>12} {ac2.ndim} \
\n{"array_size:":>12} {ac2.size} \
')

[[[1 2 3 4 5]]]
object type: <class 'numpy.ndarray'> 
  data type: int32 
      shape: (1, 1, 5) 
  dimension: 3 
 array_size: 5 


In [45]:
a_zeros = np.zeros((2,3))
print(a_zeros)
a_ones = np.ones((2,4), dtype=int)
print(a_ones)
a_full = np.full((2,5), 7)
print(a_full)
print(np.eye(4))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]]
[[7 7 7 7 7]
 [7 7 7 7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [46]:
a_ran = np.random.random((2,3,4))
print(f'{a_ran}\n{a_ran.dtype}')

[[[0.42563111 0.02369724 0.93839593 0.11748651]
  [0.11803145 0.46277468 0.64885245 0.84965387]
  [0.62249961 0.43851682 0.4535175  0.60167707]]

 [[0.11836912 0.71457656 0.95902348 0.57297608]
  [0.41428191 0.03347607 0.52796475 0.8749464 ]
  [0.38869791 0.556692   0.53953551 0.74149668]]]
float64


In [50]:
print(c)
print(c[1,0,4])
print(c[1][0][4])
print(c[0,0,4])

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]

 [[ 4  5  6  7  8]
  [10 11 12 13 14]]]
8
8
5


In [52]:
print(c)
l = []
for i in c:
    for j in i:
        for k in j:
            l.append(k)
print(f'{l}\n{np.array(l)}')
print(np.array(c.flat))

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]

 [[ 4  5  6  7  8]
  [10 11 12 13 14]]]
[1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14]
[ 1  2  3  4  5  8  9 10 11 12  4  5  6  7  8 10 11 12 13 14]
[ 1  2  3  4  5  8  9 10 11 12  4  5  6  7  8 10 11 12 13 14]


In [58]:
g = np.arange(21)
print(f'{g}\n{type(g)}')
print(g.reshape(1,3,7))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
<class 'numpy.ndarray'>
[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]]]


In [54]:
h = np.arange(5, 21, 2)
print(h)
print(np.arange(1, 21).reshape(2, 10))

[ 5  7  9 11 13 15 17 19]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [63]:
a_ss = np.linspace(0,1,3)
print(f'{a_ss}\n{a_ss.shape}\n{a_ss.size}')

[0.  0.5 1. ]
(3,)
3


In [64]:
np.array([[[1,2,3,4,5]]]).shape


(1, 1, 5)

In [67]:
xa = np.array([[1,2],[3,4],[5,6]])
xb = np.array([[3,4],[5,6],[7,8]])
print(xa.shape, xb.shape)
print(f'{xa+xb}\n {xa*2}')

(3, 2) (3, 2)
[[ 4  6]
 [ 8 10]
 [12 14]]
 [[ 2  4]
 [ 6  8]
 [10 12]]


In [78]:
xa = np.array([[1,2],[3,4],[5,6]])
xb = np.array([[3,4],[5,6],[7,8]])
print(np.add(xa, xb))
print(np.subtract(xa, xb))
print(np.multiply(xa, xb))
print(np.sqrt(xa))

[[ 4  6]
 [ 8 10]
 [12 14]]
[[-2 -2]
 [-2 -2]
 [-2 -2]]
[[ 3  8]
 [15 24]
 [35 48]]
[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]


In [82]:
xa = np.array([[1,2],[3,4],[5,6]])
xb = np.array([[3,4],[5,6],[7,8]])
xc = np.ones((2,1))
print(xc, xc.shape, xc.ndim)
print(xa.dot(xc))
print(np.dot(xb,xc))

[[1.]
 [1.]] (2, 1) 2
[[ 3.]
 [ 7.]
 [11.]]
[[ 7.]
 [11.]
 [15.]]


In [87]:
xd = np.array([[1,2],[1,2]]); print(xd)
print(np.dot(xa,xd)); print(np.dot(xb,xd))

[[1 2]
 [1 2]]
[[ 3  6]
 [ 7 14]
 [11 22]]
[[ 7 14]
 [11 22]
 [15 30]]


In [91]:
print(xa.T)
print(xb+3)
print(xb)
xb += 3
print(xb)

[[1 3 5]
 [2 4 6]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[3 4]
 [5 6]
 [7 8]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [99]:
ya = np.arange(1,10).reshape(3,3); print(ya)
yv1 = np.ones((3,1)); print(yv1)
yb = ya + yv1; print(yb)
yv2 = np.full((1,3), 2); print(yv2)
yc = ya + yv2; print(yc)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1.]
 [1.]
 [1.]]
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
[[2 2 2]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [101]:
print(yc.sum(), yc.mean(), yc.min(), yc.max(), yc.var(), yc.std())

63 7.0 3 11 6.666666666666667 2.581988897471611


In [102]:
print(yc.argmax(), yc.argmin())

8 0


In [104]:
print(yc);
print(yc.mean(axis=0), yc.mean(axis=1))

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[6. 7. 8.] [ 4.  7. 10.]


In [110]:
karray = np.arange(21).reshape(3,7); print(karray)
print(karray[0], karray[0,:4])
print(karray[:2])
print(karray[:2, :3])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[0 1 2 3 4 5 6] [0 1 2 3]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]
[[0 1 2]
 [7 8 9]]


In [115]:
karray = np.arange(21).reshape(3,7); print(karray)
print(karray[[0,2]])
print(karray[:,[1,5]])
print(karray[:,1:5])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[[ 0  1  2  3  4  5  6]
 [14 15 16 17 18 19 20]]
[[ 1  5]
 [ 8 12]
 [15 19]]
[[ 1  2  3  4]
 [ 8  9 10 11]
 [15 16 17 18]]


In [122]:
karray = np.arange(21).reshape(3,7); print(karray)
fkarray = karray.flatten()
print(fkarray, fkarray.shape)

fkarray1 = np.array(karray.flat)
print(fkarray1)

rfkarray = karray.reshape(1, 21)
print(rfkarray, rfkarray.shape)

rfkarray = karray.reshape(21, )
print(rfkarray, rfkarray.shape)

rfkarray.resize(3, 7)
print(rfkarray, rfkarray.shape)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] (21,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]] (1, 21)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] (21,)
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]] (3, 7)


In [129]:
print(karray)
karray1 = karray[:, :3]; karray2 = karray[:, 3:6]
karrayh = np.hstack([karray1, karray2]); print(karrayh)
karrayv = np.vstack([karray1, karray2]); print(karrayv)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[[ 0  1  2  3  4  5]
 [ 7  8  9 10 11 12]
 [14 15 16 17 18 19]]
[[ 0  1  2]
 [ 7  8  9]
 [14 15 16]
 [ 3  4  5]
 [10 11 12]
 [17 18 19]]


In [ ]:
15 24 